strings:
 CustomizerScript:
  label: cs
  usage: /%1
  description: 커스텀 스크립트
  permission: op

 CustomizerCommand:
  label: cc
  usage: /%1
  description: 커스텀 명령어
  permission: op

 CustomizerDialog:
  label: cd
  usage: /%1
  description: 커스텀 다이어로그
  permission: op

 CustomizerArea:
  label: ca
  usage: /%1
  description: 커스텀 지역
  permission: op

 CustomizerEntity:
  label: cen
  usage: /%1
  description: 커스텀 엔티티
  permission: op

 CustomizerEvent:
  label: cev
  usage: /%1
  description: 커스텀 이벤트
  permission: op

 CustomizerClick:
  label: cck
  usage: /%1
  description: 커스텀 클릭
  permission: op

 __Public:
  NOT_IN_GAME: 게임중에만 사용가능한 명령어입니다.
  NO_PERMISSION: 명령어를 사용할수 있는 권한이 없습니다.
  NO_PLAYER_FOUND: 플레이어가 존재하지 않습니다.
  INCORRECT_ARGUMENT: 올바르지 않은 인자값입니다.
  form:
   check_filtering: 플레이어 검색을 하시겠습니까?
   yes: 예
   no: 아니요